[package]
name = "chin-wayland-utils"
version = "0.1.0"
edition = "2024"

[dependencies]
log = { workspace = true }
niri-ipc = { git = "https://github.com/YaLTeR/niri.git", tag = "v25.08" }
chin-tools = { path = "../chin-tools" }
serde_json = "^1.0"
serde = { workspace = true }
